/* Professional three-day course shell. No WebGL, hidden interaction, or spatial navigation. */
(function(){
  'use strict';
  var root=document.getElementById('workspace'),outline=document.getElementById('outline'),sidebar=document.getElementById('learning-sidebar');
  var state=loadState(), current=null;
  function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function loadState(){try{return JSON.parse(localStorage.getItem('cryptoworld-course-state')||'{"lessons":{}}');}catch(e){return {lessons:{}};}}
  function save(){try{localStorage.setItem('cryptoworld-course-state',JSON.stringify(state));}catch(e){}}
  function record(id,patch){state.lessons[id]=Object.assign(state.lessons[id]||{},patch,{updatedAt:new Date().toISOString()});save();renderOutline();updateProgress();}
  function lessonStatus(id){return (state.lessons[id]||{}).status==='completed';}
  function progress(){return CURRICULUM.all.filter(function(l){return lessonStatus(l.id);}).length;}
  function updateProgress(){var p=Math.round(progress()/CURRICULUM.all.length*100);document.getElementById('course-progress-label').textContent=p+'% complete';}
  function route(){var hash=location.hash.replace(/^#\/?/,'');if(!hash)return {type:'home'};var m=hash.match(/^day-[123]\/([^/]+)\/([^/]+)$/);if(m&&CURRICULUM.byId[m[2]])return {type:'lesson',lesson:CURRICULUM.byId[m[2]]};return {type:'home'};}
  function go(id){location.hash=id?'#/day-'+id.day.replace('day','')+'/'+moduleFor(id)+'/'+id.id:'#/';}
  function moduleFor(lesson){return lesson.chapter==='classical'?'foundations':lesson.chapter==='symmetric'?'symmetric-core':lesson.chapter==='asymmetric'?'public-key':'future-outlook';}
  function renderOutline(){var html='<div class="outline-heading">Course outline</div><p class="outline-kicker">Three-day training programme</p>';CURRICULUM.days.forEach(function(day){var done=day.lessons.filter(function(l){return lessonStatus(l.id);}).length;html+='<section class="day-block"><h2 class="day-title">'+esc(day.number)+' · '+esc(day.title.split(' · ')[0])+'</h2><p class="day-meta">'+done+' / '+day.lessons.length+' lessons complete</p>';day.lessons.forEach(function(l,i){var active=current&&current.id===l.id?' active':'';html+='<button class="lesson-link'+active+(lessonStatus(l.id)?' done':'')+'" data-lesson="'+esc(l.id)+'"><span class="lesson-index">'+(lessonStatus(l.id)?'✓':String(i+1).padStart(2,'0'))+'</span><span>'+esc(l.title)+'<small>'+esc(l.zh)+'</small></span></button>';});html+='</section>';});outline.innerHTML=html;outline.querySelectorAll('[data-lesson]').forEach(function(b){b.onclick=function(){var l=CURRICULUM.byId[b.getAttribute('data-lesson')];go(l);outline.classList.remove('open');};});}
  function renderSide(lesson){var day=CURRICULUM.days.filter(function(d){return d.id===lesson.day;})[0],done=day.lessons.filter(function(l){return lessonStatus(l.id);}).length,p=Math.round(done/day.lessons.length*100);sidebar.innerHTML='<div class="side-block"><p class="side-title">Training day</p><strong>'+esc(day.number)+'</strong><p>'+esc(day.title)+'</p><div class="progress-track"><div class="progress-fill" style="width:'+p+'%"></div></div><span class="status">'+done+' of '+day.lessons.length+' lessons complete</span></div><div class="side-block"><p class="side-title">Objectives</p><ul><li>Explain the construction in your own words.</li><li>Observe its strength or failure mode.</li><li>Connect the idea to a real protocol.</li></ul></div><div class="side-block"><p class="side-title">Key terms</p><p>'+esc(lesson.zh)+'<br>'+esc(lesson.chapterTitle)+'</p></div><div class="side-block"><p class="side-title">Source</p><p><a class="source-link" href="'+esc(lesson.source)+'" target="_blank" rel="noopener">Read the related blog post ↗</a></p></div>';
  }
  function dayCard(day){var first=day.lessons.filter(function(l){return !lessonStatus(l.id);})[0]||day.lessons[0],done=day.lessons.filter(function(l){return lessonStatus(l.id);}).length;return '<article class="day-card"><div class="eyebrow">'+esc(day.number)+'</div><h2>'+esc(day.title.split(' · ')[0])+'</h2><p>'+esc(day.id==='day1'?'Understand the problem cryptography solves and break classical ciphers.':day.id==='day2'?'Trace AES and choose safe constructions for confidentiality and integrity.':'Build public-key protocols, signatures and a hybrid secure channel.')+'</p><div class="card-footer"><span>'+done+' / '+day.lessons.length+' complete</span><button class="primary" data-start="'+first.id+'">'+(done?'Continue':'Begin day')+'</button></div></article>';}
  function renderHome(){current=null;renderOutline();sidebar.innerHTML='<div class="side-block"><p class="side-title">Course format</p><p>Three training days. Each lesson combines explanation, a technical visualisation, a guided lab and a knowledge check.</p></div><div class="side-block"><p class="side-title">Recommended pace</p><p>Follow the outline in order during class. You may revisit any completed lesson at any time.</p></div>';root.innerHTML='<div class="eyebrow">Cryptography training · field guide</div><h1 class="page-title">Learn the systems<br>behind secure communication.</h1><p class="lead">A focused three-day introduction to classical, symmetric and asymmetric cryptography. Work through the models, break the weak constructions, and assemble the secure ones.</p><div class="dashboard-grid">'+CURRICULUM.days.map(dayCard).join('')+'</div><div class="section-label">Course method</div><p class="lesson-copy">Every lesson follows the same rhythm: understand the construction, run a controlled experiment, explain the result, then check your understanding. Toy values are deliberately visible; production cryptography requires audited implementations and careful protocol design.</p>';root.querySelectorAll('[data-start]').forEach(function(b){b.onclick=function(){go(CURRICULUM.byId[b.getAttribute('data-start')]);};});}
  function labFor(lesson){if(lesson.id==='caesar')return caesarLab();return genericLab(lesson);}
  function caesarLab(){return '<div class="lab"><h3>Caesar cipher laboratory</h3><p class="lab-instruction">Change the key and observe the substitution. Then try to recover the message by testing the small key space.</p><div class="lab-controls"><label for="caesar-message">Message</label><input id="caesar-message" type="text" value="MEET AT THE GATE"><label for="caesar-key">Key</label><input id="caesar-key" type="range" min="0" max="25" value="3"><span class="range-value" id="caesar-key-value">3</span></div><div class="lab-output" id="caesar-output" aria-live="polite"></div><div class="feedback" id="caesar-feedback">There are only 26 possible shifts, including the unchanged alphabet.</div><button class="primary" id="caesar-complete" style="margin-top:16px">Complete laboratory</button></div>';}
  function wireCaesar(lesson){var msg=root.querySelector('#caesar-message'),key=root.querySelector('#caesar-key'),out=root.querySelector('#caesar-output'),val=root.querySelector('#caesar-key-value'),feedback=root.querySelector('#caesar-feedback');function update(){val.textContent=key.value;out.textContent=Ciphers.caesarEnc(msg.value,+key.value);feedback.textContent=+key.value===0?'A zero shift changes nothing. Try several keys and compare the output.':'The same shift is applied to every letter. That regularity is exactly what makes exhaustive search possible.';}msg.oninput=update;key.oninput=update;update();root.querySelector('#caesar-complete').onclick=function(){record(lesson.id,{status:'completed',lab:true});feedback.className='feedback success';feedback.textContent='Laboratory complete. The key space is small enough to search exhaustively.';this.textContent='Laboratory completed';this.disabled=true;renderOutline();renderSide(lesson);};}
  function genericLab(lesson){var q=lesson.chapter==='classical'?'Which weakness should you investigate first?':lesson.chapter==='symmetric'?'Which statement best describes secure symmetric encryption?':lesson.chapter==='asymmetric'?'What must a public-key protocol add beyond a mathematical key exchange?':'Which statement best describes the quantum outlook?';var answers=lesson.chapter==='classical'?['The construction may expose structure or have a small key space.','A longer title makes it secure.','It cannot be attacked if the message is short.']:lesson.chapter==='symmetric'?['Use a sound construction with correct key, IV/nonce and authentication handling.','Encryption alone always proves who sent the message.','Nonce reuse is harmless with CTR.']:lesson.chapter==='asymmetric'?['Authentication and careful protocol composition.','Publishing the private key.','Using the same ephemeral key forever.']:['Quantum algorithms affect public-key assumptions differently from symmetric key search.','Quantum computers make every cipher immediately useless.','PQC is unrelated to migration planning.'];return '<div class="lab"><h3>Guided concept check</h3><p class="lab-instruction">Select the statement that best captures the lesson. The explanation is part of the exercise.</p><p><strong>'+esc(q)+'</strong></p><div class="choice-list">'+answers.map(function(a,i){return '<button class="choice" data-choice="'+i+'">'+esc(a)+'</button>';}).join('')+'</div><div class="feedback" id="choice-feedback" aria-live="polite">Choose one answer to continue.</div></div>';}
  function wireGeneric(lesson){var choices=root.querySelectorAll('[data-choice]'),feedback=root.querySelector('#choice-feedback');choices.forEach(function(b){b.onclick=function(){var correct=b.getAttribute('data-choice')==='0';choices.forEach(function(x){x.classList.remove('correct','wrong');});b.classList.add(correct?'correct':'wrong');feedback.className='feedback '+(correct?'success':'error');feedback.textContent=correct?'Correct. The construction, parameters and protocol context determine the security property.':'Not quite. Re-read the lesson objective and look for the construction or protocol assumption that can fail.';if(correct){record(lesson.id,{status:'completed',lab:true,assessment:{score:1}});renderSide(lesson);renderOutline();}};});}
  function renderLesson(lesson){current=lesson;renderOutline();renderSide(lesson);document.getElementById('mobile-lesson-label').textContent=lesson.title;var all=CURRICULUM.all,i=all.indexOf(lesson),prev=all[(i+all.length-1)%all.length],next=all[(i+1)%all.length],completed=lessonStatus(lesson.id);root.innerHTML='<div class="lesson-header"><div class="eyebrow">'+esc(lesson.number||lesson.dayTitle)+' · '+esc(lesson.kind)+'</div><h1 class="lesson-title">'+esc(lesson.title)+'</h1><div class="lesson-zh">'+esc(lesson.zh)+'</div><div class="objective"><strong>Lesson objective</strong><br>Understand the construction, observe its security trade-off, and explain the result in your own words.</div></div><div class="section-label">Concept</div><p class="lesson-copy">'+esc(lesson.body)+'</p><div class="section-label">Guided laboratory</div><div id="lab-mount">'+labFor(lesson)+'</div><div class="section-label">Takeaway</div><p class="lesson-copy">Security is a property of the construction, its parameters, and the protocol around it—not merely the name of an algorithm.</p><div class="lesson-nav"><button class="outline-button" data-nav="prev">← Previous lesson</button><button class="primary" data-nav="next">Next lesson →</button></div>';if(lesson.id==='caesar')wireCaesar(lesson);else wireGeneric(lesson);root.querySelector('[data-nav="prev"]').onclick=function(){go(prev);};root.querySelector('[data-nav="next"]').onclick=function(){go(next);};}
  function render(){updateProgress();var r=route();if(r.type==='lesson')renderLesson(r.lesson);else renderHome();}
  document.getElementById('btn-outline').onclick=function(){outline.classList.toggle('open');};document.getElementById('btn-language').onclick=function(){document.documentElement.lang=document.documentElement.lang==='en'?'zh':'en';};window.addEventListener('hashchange',render);window.addEventListener('load',render);render();
})();
