/* Application controller: full curriculum navigation, station labs, locale, persistence. */
(function(){
 var world,controls,currentStation=null,currentLesson=null,stage=null,visited={};
 var activity={gate:function(root){root.innerHTML='<h2>Welcome to CryptoWorld · 欢迎来到密码世界</h2><p class="stage-sub">A guided journey through the complete four-part cryptography series.</p><div class="stage-box">Confidentiality · Integrity · Authenticity · Availability</div><p>Open the map to browse every lesson from the blog: classical ciphers, AES modes, HMAC, RSA/OAEP, signatures, DH/PFS, ECC, hybrid encryption, Shor, Grover and PQC migration.</p>';return function(){};},caesar:ActivityCaesar,rail:ActivityRail,enigma:ActivityEnigma,aes:ActivityAES,rsa:ActivityRSA,quantum:ActivityQuantum};
 function $(id){return document.getElementById(id);}
 function station(id){return world.stations.filter(function(s){return s.id===id;})[0];}
 function anchor(chapter){return {classical:'gate',symmetric:'aes',asymmetric:'rsa',quantum:'quantum'}[chapter]||'gate';}
 function mark(id){visited[id]=true;try{localStorage.setItem('crypto3d-visited',JSON.stringify(visited));}catch(e){}}
 function openStation(id){currentStation=id;currentLesson=null;var p=station(id),info=I18N.t('islands.'+id);$('island-name').textContent=info.name;$('island-sub').textContent=info.sub;$('island-body').innerHTML='<p>'+info.desc+'</p><p class="hint2">Open the map for the complete chapter curriculum.</p>';$('island-panel').classList.remove('hidden');$('btn-start').textContent=I18N.t('start');controls.focus(p.position.clone().add(new THREE.Vector3(0,2,0)),true);AudioFX.select();}
 function openLesson(lesson){currentLesson=lesson;currentStation=null;mark(lesson.id);var p=station(anchor(lesson.chapter));$('island-name').textContent=lesson.title;$('island-sub').textContent=lesson.zh+' · '+lesson.chapterTitle;$('island-body').innerHTML='<p>'+lesson.body+'</p><p class="hint2">Source: <a href="'+lesson.source+'" target="_blank" rel="noopener">Jianqing\'s Blog</a></p>';$('island-panel').classList.remove('hidden');$('btn-start').textContent=I18N.t('start');if(p)controls.focus(p.position.clone().add(new THREE.Vector3(0,2,0)),true);AudioFX.select();}
 function launch(){if(stage){stage.remove();stage=null;}stage=document.createElement('div');stage.id='stage';document.getElementById('ui').appendChild(stage);if(currentLesson){if(activity[currentLesson.kind])activity[currentLesson.kind](stage);else ActivityCurriculum(stage,currentLesson);}else if(currentStation&&activity[currentStation])activity[currentStation](stage);$('island-panel').classList.add('hidden');}
 function lessonRow(lesson){var b=document.createElement('button');b.className='wm-row lesson-row';b.style.borderLeft='3px solid '+lesson.color;b.innerHTML='<span class="wm-name">'+lesson.title+'</span><span class="wm-desc">'+lesson.zh+'</span><span class="wm-star">'+(visited[lesson.id]?'✓':'›')+'</span>';b.onclick=function(){menuPanel().classList.add('hidden');openLesson(lesson);};return b;}
 function menuPanel(){return $('world-menu');}
 function menu(){var m=$('world-menu'),list=$('world-menu-list');list.innerHTML='<h2>'+I18N.t('map_title')+'</h2><p class="panel-sub">Complete curriculum from the four cryptography posts</p>';CURRICULUM.chapters.forEach(function(ch){var h=document.createElement('div');h.className='chapter-heading';h.innerHTML='<span class="wm-dot" style="background:'+ch.color+'"></span>'+ch.title+' <small>'+ch.lessons.length+' lessons</small>';list.appendChild(h);ch.lessons.forEach(function(raw){list.appendChild(lessonRow(CURRICULUM.byId[raw[0]]));});});m.classList.toggle('hidden');}
 function updateText(){document.documentElement.lang=I18N.lang;$('hud-title').textContent=I18N.t('app_title');$('btn-lang').textContent=I18N.t('lang_btn');$('btn-menu').textContent='☰ '+I18N.t('map');$('btn-start').textContent=I18N.t('start');}
 function boot(){try{visited=JSON.parse(localStorage.getItem('crypto3d-visited')||'{}');}catch(e){}var fill=$('loader-fill'),txt=$('loader-text');fill.style.width='35%';txt.textContent=I18N.t('load2');world=new CryptoWorld(document.querySelector('canvas'));controls=new WorldControls(world.camera,world.dom);controls.focus(new THREE.Vector3(0,2,0),true);fill.style.width='75%';txt.textContent=I18N.t('load3');world.dom.addEventListener('dblclick',function(){var best=null,dist=999;world.stations.forEach(function(s){var d=controls.target.distanceTo(s.position);if(d<dist){best=s;dist=d;}});if(best)openStation(best.id);});$('btn-lang').onclick=function(){I18N.toggle();updateText();};$('btn-menu').onclick=menu;$('btn-sound').onclick=function(){var on=AudioFX.toggle();this.classList.toggle('off',!on);};$('btn-start').onclick=launch;$('btn-prev').onclick=function(){var all=CURRICULUM.all,i=currentLesson?all.indexOf(currentLesson):0;openLesson(all[(i+all.length-1)%all.length]);};$('btn-next').onclick=function(){var all=CURRICULUM.all,i=currentLesson?all.indexOf(currentLesson):-1;openLesson(all[(i+1)%all.length]);};updateText();fill.style.width='100%';txt.textContent=I18N.t('load4');setTimeout(function(){$('loader').classList.add('done');$('hint-bar').textContent=I18N.t('hint_orbit')+' · '+CURRICULUM.all.length+' lessons';$('hint-bar').classList.remove('hidden');},450);requestAnimationFrame(loop);}
 function loop(){world.tick();requestAnimationFrame(loop);}
 if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(function(){});window.addEventListener('load',boot);
})();