/* Application controller: boot, map, station lessons, locale, persistence. */
(function(){
 var world,controls,current=null,stage=null,visited={};
 var activity={gate:function(root){root.innerHTML='<h2>Welcome to CryptoWorld · 欢迎来到密码世界</h2><p class="stage-sub">A guided journey from Caesar to post-quantum cryptography.</p><div class="stage-box">Confidentiality · Integrity · Authenticity · Availability</div><p>Cryptography turns mathematical structure into trust on an untrusted channel. Explore each island, experiment, and connect the history to modern engineering.</p>';return function(){};},caesar:ActivityCaesar,rail:ActivityRail,enigma:ActivityEnigma,aes:ActivityAES,rsa:ActivityRSA,quantum:ActivityQuantum};
 function $(id){return document.getElementById(id);} function toast(s){var t=$('toast');t.textContent=s;t.classList.remove('hidden');setTimeout(function(){t.classList.add('hidden');},2200);}
 function station(id){return world.stations.filter(function(s){return s.id===id;})[0];}
 function open(id){current=id;visited[id]=true;try{localStorage.setItem('crypto3d-visited',JSON.stringify(visited));}catch(e){}var p=station(id),info=I18N.t('islands.'+id);$('island-name').textContent=info.name;$('island-sub').textContent=info.sub;$('island-body').innerHTML='<p>'+info.desc+'</p>';$('island-panel').classList.remove('hidden');$('btn-start').textContent=I18N.t('start');controls.focus(p.position.clone().add(new THREE.Vector3(0,2,0)),true);AudioFX.select();}
 function closePanel(){$('island-panel').classList.add('hidden');}
 function launch(){if(!current)return;stage=document.createElement('div');stage.id='stage';document.getElementById('ui').appendChild(stage);activity[current](stage);$('island-panel').classList.add('hidden');}
 function menu(){var m=$('world-menu'),list=$('world-menu-list');list.innerHTML='<h2>'+I18N.t('map_title')+'</h2>';world.stations.forEach(function(s){var info=I18N.t('islands.'+s.id),b=document.createElement('button');b.className='wm-row';b.innerHTML='<span class="wm-dot" style="background:#'+s.color.toString(16)+'"></span><span class="wm-name">'+info.name+'</span><span class="wm-desc">'+info.sub+'</span><span class="wm-star">'+(visited[s.id]?'★':'☆')+'</span>';b.onclick=function(){m.classList.add('hidden');open(s.id);};list.appendChild(b);});m.classList.toggle('hidden');}
 function updateText(){document.documentElement.lang=I18N.lang;$('hud-title').textContent=I18N.t('app_title');$('btn-lang').textContent=I18N.t('lang_btn');$('btn-menu').textContent='☰ '+I18N.t('map');$('btn-start').textContent=I18N.t('start');}
 function boot(){try{visited=JSON.parse(localStorage.getItem('crypto3d-visited')||'{}');}catch(e){}var fill=$('loader-fill'),txt=$('loader-text');fill.style.width='35%';txt.textContent=I18N.t('load2');world=new CryptoWorld(document.querySelector('canvas')||document.createElement('canvas'));controls=new WorldControls(world.camera,world.dom);controls.focus(new THREE.Vector3(0,2,0),true);fill.style.width='75%';txt.textContent=I18N.t('load3');world.dom.addEventListener('dblclick',function(){var best=null,dist=999;world.stations.forEach(function(s){var d=controls.target.distanceTo(s.position);if(d<dist){best=s;dist=d;}});if(best)open(best.id);});$('btn-lang').onclick=function(){I18N.toggle();updateText();};$('btn-menu').onclick=menu;$('btn-sound').onclick=function(){var on=AudioFX.toggle();this.classList.toggle('off',!on);};$('btn-start').onclick=launch;$('btn-prev').onclick=function(){var i=world.stations.findIndex(function(s){return s.id===current;});open(world.stations[(i+world.stations.length-1)%world.stations.length].id);};$('btn-next').onclick=function(){var i=world.stations.findIndex(function(s){return s.id===current;});open(world.stations[(i+1)%world.stations.length].id);};updateText();fill.style.width='100%';txt.textContent=I18N.t('load4');setTimeout(function(){$('loader').classList.add('done');$('hint-bar').textContent=I18N.t('hint_orbit');$('hint-bar').classList.remove('hidden');},450);requestAnimationFrame(loop);}
 function loop(){world.tick();requestAnimationFrame(loop);}
 if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(function(){});window.addEventListener('load',boot);
})();