/* Procedural CryptoWorld scene. No remote assets or network dependencies. */
(function(){
 var COLORS={gate:0x59d0ff,classical:0xffca5c,enigma:0xff7e9d,symmetric:0x8ef7a5,asymmetric:0xb78cff,quantum:0x62f4ff};
 function mat(c,em){return new THREE.MeshStandardMaterial({color:c,emissive:c,emissiveIntensity:em||.25,metalness:.35,roughness:.55});}
 function World(canvas){this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x04060e);this.scene.fog=new THREE.FogExp2(0x04060e,.0038);this.camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,800);this.renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.setSize(innerWidth,innerHeight);canvas.replaceWith(this.renderer.domElement);this.dom=this.renderer.domElement;this.clock=new THREE.Clock();this.stations=[];this.glyphs=[];this.make();window.addEventListener('resize',this.resize.bind(this));}
 World.prototype.make=function(){var s=this.scene; s.add(new THREE.HemisphereLight(0x9bbcff,0x080a18,1.5));var dl=new THREE.DirectionalLight(0xffffff,1.3);dl.position.set(30,80,20);s.add(dl);var stars=new THREE.BufferGeometry(),arr=[];for(var i=0;i<900;i++){var r=220*Math.random()+50,a=Math.random()*Math.PI*2,b=Math.acos(2*Math.random()-1);arr.push(r*Math.sin(b)*Math.cos(a),r*Math.cos(b),r*Math.sin(b)*Math.sin(a));}stars.setAttribute('position',new THREE.Float32BufferAttribute(arr,3));s.add(new THREE.Points(stars,new THREE.PointsMaterial({color:0x8caeff,size:.65,sizeAttenuation:true})));
  this.island('gate','gate',0,0,0,12);this.island('caesar','classical',-35,0,-20,14);this.island('rail','classical',35,0,-20,14);this.island('enigma','enigma',0,0,-52,14);this.island('aes','symmetric',-35,0,24,15);this.island('rsa','asymmetric',35,0,24,15);this.island('quantum','quantum',0,0,57,15);this.connect();for(var i=0;i<35;i++){var g=Text3D.label(['A','0','1','∑','π','◇'][i%6],i%2?'#678bff':'#59d0ff');g.position.set((Math.random()-.5)*150,Math.random()*35+4,(Math.random()-.5)*150);g.scale.set(2.1,0.55,1);s.add(g);this.glyphs.push(g);}}
 World.prototype.connect=function(){var pairs=[[[0,0,0],[-35,0,-20]],[[0,0,0],[35,0,-20]],[[0,0,0],[0,0,-52]],[[0,0,0],[-35,0,24]],[[0,0,0],[35,0,24]],[[0,0,0],[0,0,57]]];for(var j=0;j<pairs.length;j++){var a=new THREE.Vector3().fromArray(pairs[j][0]),b=new THREE.Vector3().fromArray(pairs[j][1]),d=b.clone().sub(a),m=new THREE.Mesh(new THREE.BoxGeometry(2,.35,d.length()),mat(0x172b58,.2));m.position.copy(a.clone().add(b).multiplyScalar(.5));m.rotation.y=Math.atan2(d.x,d.z);this.scene.add(m);}}
 World.prototype.island=function(id,region,x,y,z,r){var group=new THREE.Group();group.position.set(x,y,z);var base=new THREE.Mesh(new THREE.CylinderGeometry(r,r*.78,3.5,48),mat(0x111b36,.1));base.position.y=-1.75;group.add(base);var top=new THREE.Mesh(new THREE.CylinderGeometry(r*.88,r*.88,.55,48),mat(COLORS[region],.18));top.position.y=.1;group.add(top);var ring=new THREE.Mesh(new THREE.TorusGeometry(r*.72,.12,8,64),mat(COLORS[region],.8));ring.rotation.x=Math.PI/2;ring.position.y=.5;group.add(ring);var pillar=new THREE.Mesh(new THREE.OctahedronGeometry(2.8,1),mat(COLORS[region],.65));pillar.position.y=3;pillar.rotation.y=.4;group.add(pillar);var l=Text3D.label(id.toUpperCase(),region==='classical'?'#ffca5c':'#8ef7a5');l.position.y=8;group.add(l);this.scene.add(group);this.stations.push({id:id,group:group,position:group.position.clone(),color:COLORS[region]});};
 World.prototype.resize=function(){this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight);};
 World.prototype.tick=function(){var t=this.clock.getElapsedTime();for(var i=0;i<this.glyphs.length;i++)this.glyphs[i].position.y+=Math.sin(t*.4+i)*.002;for(var j=0;j<this.stations.length;j++){var g=this.stations[j].group;g.children[2].rotation.z=t*.25+j;g.children[3].rotation.y=t*.2;}this.renderer.render(this.scene,this.camera);};
 window.CryptoWorld=World;
})();